name: Swift Test

on:
  push:
    branches:
      - main
    tags: 
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches-ignore:
      - *
    tags-ignore:
      - *

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
